#!/bin/sh

set -e

cd "${WORKDIR}"
source .env

pushd "${TARGET_DIR}"
echo "${FUNCTION_SPEC}" > function.yaml
popd

# 1. Commit and Push
git add "${TARGET_DIR}"
if git diff-index --quiet HEAD; then
  echo "No changes detected for this iteration."
else
  git commit -m "Update function: ${FUNCTION_HOST}/${FUNCTION_NAME}:${FUNCTION_GENERATION}"
  git push origin "${BRANCH_NAME}"
fi
