#!/bin/sh

set -e

cd "${PACKAGING_DIR}"

tar -cf layer.tar --exclude=layer.tar .

DIFF_ID=$(sha256sum layer.tar | awk '{print $1}')

gzip -c layer.tar > layer.tar.gz

DIFF_IDS="\"sha256:$DIFF_ID\""
IMPORTMAP_LAYER=""
ARTIFACT_TYPE_ARG=""
if [ -f "importmap.json" ]; then
    # Create a proper layer for the importmap to satisfy containerd parity requirements
    tar -cf importmap.layer.tar importmap.json
    IMPORTMAP_DIFF_ID=$(sha256sum importmap.layer.tar | awk '{print $1}')
    gzip -f importmap.layer.tar
    
    DIFF_IDS="${DIFF_IDS}, \"sha256:$IMPORTMAP_DIFF_ID\""
    ARTIFACT_TYPE_ARG="--artifact-type application/vnd.kdex.importmap+json"
    IMPORTMAP_LAYER="importmap.layer.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip"
fi

cat <<EOF > config.json
{
    "architecture": "amd64",
    "os": "linux",
    "rootfs": {
        "type": "layers",
        "diff_ids": [$DIFF_IDS]
    }
}
EOF

# if IMAGE_REGISTRY domain ends with .local, use --plain-http

# if IMAGE_REGISTRY doesn't contain a protocol separator, add it
case "$IMAGE_REGISTRY" in
    *://*)
        ;;
    *)
        IMAGE_REGISTRY="//${IMAGE_REGISTRY}"
        ;;
esac

REG_DOMAIN=$(durl +%D "${IMAGE_REGISTRY}")
echo "REG_DOMAIN: ${REG_DOMAIN}"
case "$REG_DOMAIN" in
    *.local|k3d-registry)
        ORAS_ARGS="${ORAS_ARGS} --plain-http"
        ;;
    *)
        ;;
esac

IMAGE_REGISTRY=$(durl +%H "${IMAGE_REGISTRY}")

# if IMAGE_PULL_SECRET exists, use --config
if [ "${IMAGE_PULL_SECRET}x" != "x" ]; then
    ORAS_ARGS="${ORAS_ARGS} --config ${IMAGE_PULL_SECRET}"
fi

CMD="oras push ${ORAS_ARGS} \
    ${ARTIFACT_TYPE_ARG} \
    --config config.json:application/vnd.oci.image.config.v1+json \
    --export-manifest manifest.json \
    ${IMAGE_URL} \
    layer.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip \
    --annotation io.deis.oras.content.unpack=true \
    ${IMPORTMAP_LAYER}"

echo "CMD: ${CMD}"

${CMD}

IMAGE_DIGEST=$(sha256sum manifest.json | awk '{print $1}')
FULL_REFERENCE="sha256:${IMAGE_DIGEST}"

echo "========== Image Manifest ===================="
cat manifest.json
printf "\n==============================================\n"
echo "Artifact Digest: ${FULL_REFERENCE}"

if [ -w /dev/termination-log ]; then
    echo "${FULL_REFERENCE}" > /dev/termination-log
fi