#!/bin/sh

set -e

cd "${WORKDIR}"
source .env

APISERVER="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"
TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
CACERT="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

# Remove any authority from the REPOSITORY URL
REPOSITORY=$(git remote get-url --push origin)
REPOSITORY=$(gurl +%S%H%p ${REPOSITORY})

DATA=$(cat <<EOF
{
	"status": {
		"state": "ExecutableAvailable",
		"executable": "${IMAGE}",
		"detail": "Executable: ${IMAGE}"
	}
}
EOF
)

RESPONSE=$(\
	curl ${APISERVER}/apis/kdex.dev/v1alpha1/namespaces/${FUNCTION_NAMESPACE}/kdexfunctions/${FUNCTION_NAME}/status \
		-s -w "%{http_code}" \
		--cacert "${CACERT}" \
		-X PATCH \
		-H "Content-Type: application/merge-patch+json" \
		-H "Authorization: Bearer ${TOKEN}" \
		--data "${DATA}")

HTTP_CODE="${RESPONSE:${#RESPONSE}-3}"
CONTENT="${RESPONSE:0:${#RESPONSE}-3}"

echo "Status Code: ${HTTP_CODE}"
echo "Response Body: ${CONTENT}"

if [ "${HTTP_CODE}" -eq 200 ]; then
	echo "Success!"
else
	echo "Status update failed with error."
	exit 1
fi
